server:
  port: 8084

spring:
  application:
    name: event-queue
  datasource:
    url: jdbc:mysql://localhost:3307/neuropace
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
